services:
  redis:
    image: redis:8.2.1
    networks:
      - candomble_network
    volumes:
      - candomble_redis:/data
    ports:
      - 127.0.0.1:6379:6379

  redisinsight:
    image: redis/redisinsight:2.54
    networks:
      - candomble_network
    volumes:
      - candomble_redis_insight:/root/.redisinsight
    ports:
      - "127.0.0.1:5540:5540"

  webserver:
    image: nginx:alpine
    container_name: nginx_candomble
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - candomble_webserver:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - candomble_network

  candomble:
    build:
      context: .
      tags:
        - candomble-core:development
    volumes:
      - ./app:/var/www/html/app:ro
      - ./bootstrap/app.php:/var/www/html/bootstrap/app.php:ro
      - ./config:/var/www/html/config:ro
      - ./database:/var/www/html/database:rw
      - ./public:/var/www/html/public:ro
      - ./resources:/var/www/html/resources:ro
      - ./routes:/var/www/html/routes:ro
      - ./storage:/var/www/html/storage:rw
    networks:
      - candomble_network
    working_dir: /var/www/html
    environment:
      DEVELOPER_UID_OVERRIDE: '${DEVELOPER_UID_OVERRIDE}'
      DEVELOPER_GID_OVERRIDE: '${DEVELOPER_GID_OVERRIDE}'
    env_file:
      - .env

  mysql:
    image: mysql:9.2.0
    container_name: candomble_mysql
    networks:
      - candomble_network
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    volumes:
      - candomble_mysql:/var/lib/mysql

networks:
  candomble_network:
    name: candomble
  
volumes:
  user:
    driver: local
  candomble_redis:
    driver: local
  candomble_mysql:
    driver: local
  candomble_redis_insight:
    driver: local
  candomble_webserver:
    driver: local